[tool.poetry]
name = "difficult-rocket"
version = "0.6.5.0"
description = "A rocket game"
authors = ["shenjackyuanjie <3695888@qq.com>"]
license = "CC-BY-NA-SA 4.0"
readme = "README.md"
packages = [{include = "difficult_rocket"}]

[tool.poetry.dependencies]
python = ">=3.8"
psutil = "^5.9.3"
objprint = "^0.2.2"
Pillow = "^9.2.0"
tomlkit = "^0.11.6"
rtoml = "^0.8.0"
setuptools = "^65.5.0"
viztracer = "^0.15.4"
vizplugins = "^0.1.2"
Cython = "^0.29.32"
defusedxml = "*"


[build-system]
requires = ["setuptools>=61",
            "wheel",
            "nuitka",
            "imageio",
            "setuptools-rust"]
build-backend = "nuitka.distutils.Build"

[project]
name = 'Difficult_Rocket'
dynamic = ['version']
authors = [
    {name = 'shenjackyuanjie', email = '3695888@qq.com'}
]
description = 'A rocket simlater'
readme = 'README.md'
requires-python = '>=3.8'
license = {text = 'CC BY-NC-SA 4.0'}
dependencies = [
    'nuitka=1.3.x',
    'psutil=5.9.x',
    'defusedxml=0.7.x',
    'rtoml=0.9.x',
    'tomlkit=0.11.x',
    'Pillow',
    'pymunk'
]
