[book]
authors = ["shenjack"]
language = "zh-cn"
multilingual = false
src = "src"
title = "Difficult-Rocket-docs"

[build]
build-dir = './docs'
create-missing = false
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds

[output.html]
input-404 = "404.md"
additional-css = ["open-in.css"]
# cname = 'hws.shenjack.top'

# Required: Your repository URL used in the link.
git-repository-url = "https://github.com/shenjackyuanjie/Difficult-Rocket"

# Your git branch. Defaults to `main`
git-branch = "main"

# The text to use in the footer.
# The link text is marked by `[]`
open-on-text = "Found a bug? [Edit this page on GitHub.]"

[output.html.search]
limit-results = 15

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

# [output.copy-resources]
# optional = true
# command = 'python output.py'

[rust]
edition = "2021"   # the default edition for code blocks

