logger_version = '1.0.0'

[Loggers]

    [Loggers.root]
    level = 'DEBUG'
    color = 'main_color'
    file = 'main_log_file'
    handlers = ['main_std_handler']

    [Loggers.client]
    level = 'TRACE'
    color = 'main_color'
    file = 'main_log_file'
    handlers = ['main_std_handler']

    [Loggers.server]
    level = 'TRACE'
    color = 'DiGua_color'
    file = 'main_log_file'
    handlers = ['main_std_handler']

[Files]
    
    [Files.main_log_file]
    name = './logs/{long_time}_logs.md'
    level = 'TRACE'
    cache_len = 20
    cache_time = 1
    mode = 'a'
    encoding = 'utf-8'

[Handler]

    [Handler.main_std_handler]
    class = 'str handler'
    format = 'format.main_format'

    [Handler.main_file_hander]
    class = 'cached file handler'
    format = 'format.main_format'

[Formatter]

main_format = '[{long_time}] [{logger_name}] {level} | {file_name}:{code_line} | {message}'
file_name = 'no frame'
code_line = 'no frame'
short_time = '%Y-%m-%d %H-%M-%S'
long_time = '%Y-%m-%d %H-%M-%S:%%S'

[Colors]

    [Colors.main_color]
    main_time = '\u001b[38;2;201;222;56m'
    code_line = '\u001b[38;2;0;255;180m'
    file_name = '\u001b[38;2;0;255;180m'
    info      = '\u001b[0m'
    message   = '\u001b[0m'
    logger    = '\u001b[0m'
    marker    = '\u001b[0m'
        TRACE.info =   '\u001b[38;2;138;173;244m'
        FINE.info =    '\u001b[35;48;2;44;44;54m'
        DEBUG.info =   '\u001b[38;2;133;138;149m'
        INFO.info =    '\u001b[0m'
        WARNING.info = '\u001b[33m'
        ERROR.info =   '\u001b[31m'
        FATAL.info =   '\u001b[38;2;255;255;0;48;2;120;10;10m'
        FATAL.logger = '\u001b[38;2;245;189;230m'
    
    [Colors.fancy_main_color]
    main_time = '\u001b[38;2;201;222;56m'
    file_name = '\u001b[38;2;0;255;180m'
    code_line = '\u001b[38;2;0;255;180m'
    info      = '\u001b[0m'
    message   = '\u001b[0m'
    logger    = '\u001b[0m'
    marker    = '\u001b[0m'
        TRACE.info =    '\u001b[38;2;138;173;244m'
        TRACE.message = '\u001b[38;2;138;173;244m'
        FINE.info =     '\u001b[35;48;2;44;44;54m'
        FINE.message =  '\u001b[35m'
        DEBUG.info =    '\u001b[38;2;133;138;149m'
        INFO.info =     '\u001b[0m'
        WARNING.info =  '\u001b[33m'
        ERROR.info =    '\u001b[31m'
        FATAL.info =    '\u001b[38;2;255;255;0;48;2;120;10;10m'
        FATAL.message = '\u001b[38;2;255;255;0;48;2;120;10;10m'
        FATAL.logger =  '\u001b[38;2;245;189;230m'
