version = 1.0

# [Loggers]

[Loggers.root]
level = 'DEBUG'
color = 'main_color'
file = 'main_log_file'

[Loggers.client]
level = 'TRACE'
color = 'main_color'
file = 'main_log_file'

[Loggers.server]
level = 'TRACE'
color = 'DiGua_color'
file = 'main_log_file'

[Files]

[Colors]

[Formatter]
