[runtime]
fps = 60
version = "0.6.1"
language = "zh-CN"
date_fmt = '%Y-%m-%d %H-%M-%S'
write_py_v = "3.8.10"
fonts_folder = 'libs/fonts'

[window]
style = "None"
width = 1300
height = 931
visible = true
caption = "Difficult Rocket {version}"
resizable = true
full_screen = false

[window.default]
width = 1024
height = 768

