language = "English"

[main]
version.now_on = "Difficult Rocket is running on Python Vision"
version.need3p = "Difficult Rocket depends on Python vision 3.0+"
version.best38p = "Difficult Rocket is writen in Python {write_py_v}, and now is running on Python {py_v} may cause BUG"
lang.language = "English (EN-US)"
logger.language = "Logging language is: "
logger.created = "Log handler created"
logger.mkdir = "logs/ folder not found, now created"
logger.main_done = "Main log handler created "
logger.logfile_name = "Log file name : "
logger.logfile_level = "Log file record level : "
logger.logfile_fmt = "Log file record format : "
logger.logfile_datefmt = "Log file date format : "
game_start.at = "The main thread of the game starts with : "

[client]
setup.done = "Client loaded"
setup.use_time = "Client loading has used: {} second"
setup.use_time_ns = "Client loading has used: {} nano second"

[window]
setup.done = "Window loaded"
setup.use_time = "Window loading has used: {} second"
setup.use_time_ns = "Window loading has used: {} nano second"
os.pid_is = "Window's PID: {} PPID: {}"
button.been_press = "Button pressed, the current state of the button is: "
mouse.press = "mouse was click at {} button is: {}"
mouse.release = "mouse release at {} button is: {}"
mouse.RIGHT = "right button"
mouse.LEFT = "left button"
mouse.MIDDLE = "middle button"
key.press = "key {} | {} been press"
key.release = "key {} | {} been release"
text.input = "input text \"{}\""
text.new_line = "new line"
text.motion = "text move {}"
text.motion_select = "text select {}"
command.text = "input command: {}"
message.text = "input message: {}"
libs.local = "using local pyglet, version: {}"
libs.outer = "using global pyglet, version: {}\n(may cause bug)"
fonts.found = "found fonts in font lib: {}"
fonts.load = "loading fonts: {}"
game.stop_get = "Received closing commands from {}, game closing"
game.stop = "game closing, saving data……"
game.end = "game closed"

[server]
setup.done = "Server loaded "
os.pid_is = "Server PID: {} PPID: {}"

[game]
input = "console"
command = "in game commands"
window = "window"
